"use client";

import { useEffect, useState } from "react";

type TenantEmailConnection={status:"Not connected"|"Connected"|"Needs reconnection"|"Connection failed";connected:boolean;tenantConnected:boolean;activeForSending:boolean;email:string;tenantEmail:string;userEmail:string;testRecipient:string;deliveryMode:"test"|"live";provider:string;googleAvailable:boolean;microsoftAvailable:boolean;lastSuccessfulUse:string;connections:{provider:string;email:string;status:string;activeForSending:boolean;connectedAt:string;lastSuccessfulUse:string}[];legacy:{connected:boolean;email:string;deliveryMode:"test"|"live";protected:boolean};error?:string};

export function EmailSettingsCard({flash}:{flash:(message:string)=>void}){
  const [connection,setConnection]=useState<TenantEmailConnection|null>(null),[busy,setBusy]=useState(false);
  const load=()=>fetch("/api/email/status").then(async response=>{const result=await response.json() as TenantEmailConnection;if(!response.ok)throw new Error(result.error||"Email status is unavailable");setConnection(result)}).catch(error=>flash(error instanceof Error?error.message:"Email status is unavailable"));
  useEffect(()=>{void load()},[]);
  const test=async()=>{if(busy)return;setBusy(true);try{const response=await fetch("/api/email/test",{method:"POST"}),result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"The safe test could not be sent");flash(`Safe test sent to ${connection?.testRecipient||"your signed-in email"}`);await load()}catch(error){flash(error instanceof Error?error.message:"The safe test could not be sent")}finally{setBusy(false)}};
  const disconnect=async()=>{if(busy)return;setBusy(true);try{const response=await fetch("/api/email/disconnect",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({provider:connection?.provider})}),result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"The email account could not be disconnected");flash("Business email account disconnected");await load()}catch(error){flash(error instanceof Error?error.message:"The email account could not be disconnected")}finally{setBusy(false)}};
  const connected=connection?.tenantConnected,status=connection?.status||"Checking connection";
  return <section className="panel tenant-email-settings">
    <header className="email-settings-heading"><div><span className="section-kicker">Business email setup</span><h3>Connect your business email</h3><p>Choose the Google or Microsoft account you normally use for the tennis business. Tennis Growth Admin will send customer messages and invoice PDFs from that address.</p></div><span className={`email-readiness ${connected&&connection?.activeForSending?"ready":"setup"}`}>{connected&&connection?.activeForSending?"Ready to send":"Setup required"}</span></header>
    <div className="email-setup-journey" aria-label="Email connection steps"><span className={connected?"done":"current"}><b>1</b>Choose provider</span><span className={connected?"done":""}><b>2</b>Approve account</span><span className={connection?.activeForSending?"done":connected?"current":""}><b>3</b>Send safe test</span><span className={connection?.activeForSending?"current":""}><b>4</b>Select Test or Live</span></div>
    {connected?<div className="connected-email-card"><span className={`provider-logo ${connection?.provider?.toLowerCase()}`}>{connection?.provider==="Microsoft"?"M":"G"}</span><div><small>{connection?.provider} connected ✓</small><strong>{connection?.tenantEmail}</strong><span>Safe tests go to {connection?.testRecipient}. Customer addresses are used only when Live mode is deliberately selected.</span></div></div>:<div className="provider-choice"><article className="provider-card available"><span className="provider-logo google">G</span><div><strong>Google</strong><small>Gmail or Google Workspace</small></div><a className="primary button-link" href="/api/email/google/connect">Connect Google</a></article><article className={`provider-card ${connection?.microsoftAvailable?"available":""}`}><span className="provider-logo microsoft">M</span><div><strong>Microsoft</strong><small>Outlook or Microsoft 365</small></div>{connection?.microsoftAvailable?<a className="primary button-link" href="/api/email/microsoft/connect">Connect Microsoft</a>:<><button className="secondary" disabled>Being activated</button><small className="provider-help">Nothing is required from Jake yet. Tennis Growth completes this once for the platform.</small></>}</article><article className="provider-card"><span className="provider-logo other">@</span><div><strong>Another provider</strong><small>For other hosted business email</small></div><button className="secondary" disabled title="Secure provider setup is being prepared">Coming later</button></article></div>}
    {connected&&<div className="email-connection-controls"><div className={`connection-status ${connection?.activeForSending?"connected":status==="Needs reconnection"||status==="Connection failed"?"attention":"neutral"}`}><span>{connection?.activeForSending?"✓":"!"}</span><strong>{connection?.activeForSending?"Connected and tested":status}</strong>{connection?.lastSuccessfulUse&&<small>Last successful use {new Date(connection.lastSuccessfulUse).toLocaleString("en-GB")}</small>}</div><div className="email-settings-actions"><button className="primary" disabled={busy} onClick={()=>void test()}>{busy?"Sending safe test…":"Send safe test"}</button><a className="secondary button-link" href={connection?.provider==="Microsoft"?"/api/email/microsoft/connect":"/api/email/google/connect"}>Change account</a><button className="secondary danger-soft" disabled={busy} onClick={()=>void disconnect()}>Disconnect</button></div></div>}
    <footer><div><strong>Rob&apos;s current Gmail route remains protected</strong><span>{connection?.legacy.connected?`Fallback available as ${connection.legacy.email}`:"Existing fallback remains stored separately"}</span></div><span className="traffic green">Preserved</span></footer>
  </section>
}
